-- ميزات ذِكرى الاحترافية V8
-- شغّل هذا الملف مرة واحدة داخل Supabase SQL Editor.

create table if not exists public.memorial_photos (
  id uuid primary key default gen_random_uuid(),
  memorial_id uuid not null references public.memorials(id) on delete cascade,
  photo_url text not null,
  caption text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.memorial_prayers (
  id uuid primary key default gen_random_uuid(),
  memorial_id uuid not null references public.memorials(id) on delete cascade,
  prayer_text text not null check (char_length(prayer_text) between 2 and 400),
  is_approved boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.quran_pledges (
  id bigint generated by default as identity primary key,
  memorial_id uuid not null references public.memorials(id) on delete cascade,
  surah_number integer not null check (surah_number between 1 and 114),
  created_at timestamptz not null default now()
);

create index if not exists memorial_photos_memorial_idx on public.memorial_photos(memorial_id);
create index if not exists memorial_prayers_memorial_idx on public.memorial_prayers(memorial_id, created_at desc);
create index if not exists quran_pledges_memorial_idx on public.quran_pledges(memorial_id);

alter table public.memorial_photos enable row level security;
alter table public.memorial_prayers enable row level security;
alter table public.quran_pledges enable row level security;

drop policy if exists "public read memorial photos" on public.memorial_photos;
create policy "public read memorial photos" on public.memorial_photos for select using (true);
drop policy if exists "admins manage memorial photos" on public.memorial_photos;
create policy "admins manage memorial photos" on public.memorial_photos for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "public read approved prayers" on public.memorial_prayers;
create policy "public read approved prayers" on public.memorial_prayers for select using (is_approved = true);
drop policy if exists "public add prayers" on public.memorial_prayers;
create policy "public add prayers" on public.memorial_prayers for insert to anon, authenticated with check (is_approved = true);
drop policy if exists "admins manage prayers" on public.memorial_prayers;
create policy "admins manage prayers" on public.memorial_prayers for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "public read quran pledges" on public.quran_pledges;
create policy "public read quran pledges" on public.quran_pledges for select using (true);
drop policy if exists "public add quran pledges" on public.quran_pledges;
create policy "public add quran pledges" on public.quran_pledges for insert to anon, authenticated with check (true);

grant select on public.memorial_photos, public.memorial_prayers, public.quran_pledges to anon, authenticated;
grant insert on public.memorial_prayers, public.quran_pledges to anon, authenticated;
grant insert, update, delete on public.memorial_photos, public.memorial_prayers, public.quran_pledges to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

select 'Zikra V8 professional features installed successfully' as result;
